<a href="https://colab.research.google.com/github/ajitpadole/Python_practice/blob/main/YOUTUBE_PYTHON_PRCTICE_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Add two numbers
num1 = int(input("Enter first Number"))
num2 = int(input("Enter Second Number"))
add = num1 + num2
print("the addition of 1 and 2 number",add)

Enter first Number10
Enter Second Number20
the addition of 1 and 2 number 30


In [ ]:
# calculate squree root program in python
def sq_root(num):
    if num > 1:
        return (num ** (1/2))


In [ ]:
num = int(input("Enter number for squree root "))
print(sq_root(num))

Enter number for squree root 63
7.937253933193772


In [ ]:
import math

a = int(input())
sqrot = math.sqrt(b)
print(sqrot)

2
5.0


In [ ]:
# calculate area of traingle
def area_traingle(b,h):
    print((0.5)* (b)*(h))
    

In [ ]:
b = int(input())
h = int(input())
area=area_traingle(b,h)
print(area)

15
42
315.0
None


In [ ]:
# swap two variable 

a = 2
b = 5
# swap wusing 3 rd variable
c=a
a=b
b=c
print(a)
print(b)

5
2


In [ ]:
# swap two variable without 3rd variable 
a=5
b=6
a,b = b,a
print(a)
print(b)

6
5


In [ ]:
# kilometer to mails 
def km_mils(num):
    print(0.62*num)
num = int(input())
print(km_mils(num))

15
9.3
None


In [ ]:
# number is positive nigative or zero
def p_n_z(num):
    if num > 0:
        return "positive"
    elif num == 0:
        return "Zero"
    else:
        return "negative"
num = int(input())
print(p_n_z(num))

0
Zero


In [ ]:
# odd or even
def is_odd(num):
    if num % 2 == 0:
        return "the number is even"
    else:
        return "the number is odd"
num = int(input())
print(is_odd(num))

25
the number is odd


In [ ]:
# check leap year 

year = int(input())

if ((year % 100 ==0 )and(year%400 == 0)):
    print("the year is leap year")
elif (year%4 ==0 )and (year%100!=0):
    print("the year is leap year")
else:
    print("the number is not leap year")

2020
the year is leap year


In [ ]:
# find largest amoung three number
num1 = int(input())
num2 = int(input())
num3 = int(input())

if ((num1>num2)and(num1>num3)):
    print("the gatest number amoung three is: ",num1)
elif ((num2>num3)and(num2>num1)):
    print("the gatest number amoung three is: ",num2)
else:
     print("the gatest number amoung three is: ",num3)
    
    

50
12
35
the gatest number amoung three is:  50


In [ ]:
# cheach prime number
num = int(input())
if num == 1:
    print( "its not prime number")
if num>1:
    for i in range(2,num):
        if num % i == 0:
            print("Not prime")
            break
        
    else:
        print("prime")


12
Not prime


In [ ]:
num = int(input())
for i in range(2,num):
        if num % i == 0:
            print("Not prime")
            break
        
else:
    print("prime")

ValueError: invalid literal for int() with base 10: ''

In [ ]:
# prime number in the range
def prime_rang(num1,num2):
    for num in range(num1,num2+1):
        if num >1:
            for i in range(2,num):
                if num%i ==0:
                    break
            else :
                print(num)


In [ ]:
print(prime_rang(15,60))

17
19
23
29
31
37
41
43
47
53
59
None


In [ ]:
# find the factorail of number 
num = int(input("The value is "))
fact = 1

for i in range(1,num+1):
    fact = i*fact
    print("the factorial is",fact)


The value is 5
the factorial is 1
the factorial is 2
the factorial is 6
the factorial is 24
the factorial is 120


In [ ]:
# find the factorail of number 
num = int(input("The value is "))
fact = 1

for i in range(1,num+1):
    fact = i*fact
print("the factorial is",fact)

The value is 5
the factorial is 120


In [ ]:
def fact(a):
    if a== 0:
        return 1
    else:
        return ((a)*fact(a-1))

In [ ]:
print(fact(5))

120


In [ ]:
# multiplication table 
num = int(input("which table required enter here"))
for i in range(1,11):
    print(i*num)

which table required enter here8
8
16
24
32
40
48
56
64
72
80


In [ ]:
# febonacci sequence
num = int(input(" the fibonacci number requred enter here "))
a= 0
b= 1
if num == 1:
    print ( "the number febonacci is 0")
if num > 1:
    print(a)
    print(b)
    for i in range(2,num):
        c = a+b
        a=b
        b=c
        print(c)

 the fibonacci number requred enter here10
0
1
1
2
3
5
8
13
21
34


In [ ]:
#sum of natural Number
num = int(input("Enter Number  ")) # Enter any number
if num <0:
    print("please enter valied positive number")
else:
    sum = 0
    while num > 0:
        sum += num
        num -= 1
    print(sum)
    


Enter Number  5
15


In [ ]:
# desplay the Power of 2
num = int(input("Enter the valied number"))
result  = list(map(lambda x:x**2,range(num+1)))
print(result)

Enter the valied number5
[0, 1, 4, 9, 16, 25]


In [ ]:
# desplay the Power of 2
num = int(input("Enter the valied number"))
result  = list(map(lambda x:2**x,range(num+1)))
print(result)

Enter the valied number5
[1, 2, 4, 8, 16, 32]


In [ ]:
# number divided by 13
num = int(input())
for i in range(1,100):
    if i % num == 0:
        print(i)

13
13
26
39
52
65
78
91


In [ ]:
# use lambada
l=[13,5,4,8,9,78,9,6,5,4,1,23,5,6,65,488,5]
result = list(filter(lambda x : x%13==0,l))
print(result)

[13, 78, 65]


In [ ]:
# convert bin,oct,hexa
num = int(input())
binary = bin(num)
octaore = oct(num)
hexa = hex(num)
print(binary)
print(octaore)
print(hexa)

150
0b10010110
0o226
0x96


In [ ]:
#Numpy Intro

In [ ]:
import numpy as np

# we have a function arange() which makes an array of the specified dimension. Example:
myArray = np.arange(20)
print(myArray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
# an array from 10 to 20
myArray = np.arange(10, 20) # [10 11 12 13 14 15 16 17 18 19]
print(myArray)

[10 11 12 13 14 15 16 17 18 19]


In [ ]:
# an array from 10 to 20 with 2 steps
myArray = np.arange(10, 20, 2)
print(myArray)  

[10 12 14 16 18]


In [ ]:
# reshape() helps to reshape our NumPy array
myArray = np.arange(20)
# syntax: reshape(number_of_rows, number_of_columns)
myArray = myArray.reshape(4, 5)
print(myArray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [ ]:
# shape returns the shape of the array. The length of shape tuple is called as rank (or dimension)
print(myArray.shape) 

(4, 5)


In [ ]:
# ndim returns the dimension (rank) of the array
print(myArray.ndim) 

2


In [ ]:
# size returns the total number of elements in the array
print(myArray.size)  

20


In [ ]:
# zeros creates an array will all zeros
myArray = np.zeros((3, 4))
print(myArray)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# ones creates an array with all ones
myArray = np.ones((3, 4))
print(myArray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# numpy random module helps to initialize array with random values
myArray = np.random.rand(3, 4)
print(myArray)

[[0.12705862 0.77521658 0.82430625 0.27939491]
 [0.61865471 0.73019916 0.48108739 0.13511539]
 [0.22358871 0.50419645 0.32795105 0.59384514]]
